title: Open Credentialing Initiative | Marketplace
description: OCI-committed service providers work together to deliver DSCSA Authorized Trading Partner (ATP) credentialing.
show_downloads: true
theme: jekyll-theme-cayman
